"""Initial migration.

Revision ID: 3c2b11dc53ef
Revises: 96e74d021614
Create Date: 2025-04-04 23:18:06.776448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c2b11dc53ef'
down_revision = '96e74d021614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_order_vo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('user_order_vo_ibfk_2', type_='foreignkey')
        batch_op.drop_column('price')
        batch_op.drop_column('product_id')
        batch_op.drop_column('quantity')
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_order_vo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('user_order_vo_ibfk_2', 'product_table', ['product_id'], ['product_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('status')
        batch_op.drop_column('final_price')

    # ### end Alembic commands ###
