"""Initial migration.

Revision ID: 96e74d021614
Revises: 0baf957fb77f
Create Date: 2025-04-04 11:14:42.745111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e74d021614'
down_revision = '0baf957fb77f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_register', schema=None) as batch_op:
        batch_op.drop_index('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_register', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=False)

    # ### end Alembic commands ###
