"""Added image column to Category

Revision ID: b48af6f1809e
Revises: 
Create Date: 2025-03-25 15:08:33.177810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48af6f1809e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_image_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('product_image_path', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_table', schema=None) as batch_op:
        batch_op.drop_column('product_image_path')
        batch_op.drop_column('product_image_name')

    # ### end Alembic commands ###
