"""Renamed columns in Category table

Revision ID: ba4abfa9bc24
Revises: b48af6f1809e
Create Date: 2025-03-25 16:13:32.345091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba4abfa9bc24'
down_revision = 'b48af6f1809e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_image_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('category_image_path', sa.String(length=255), nullable=False))
        batch_op.drop_column('product_image_path')
        batch_op.drop_column('product_image_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_image_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('product_image_path', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('category_image_path')
        batch_op.drop_column('category_image_name')

    # ### end Alembic commands ###
