"""Initial migration.

Revision ID: c8ac05631524
Revises: 3c2b11dc53ef
Create Date: 2025-04-05 16:19:28.318122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ac05631524'
down_revision = '3c2b11dc53ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_order_vo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_order_vo', schema=None) as batch_op:
        batch_op.drop_column('current_date')

    # ### end Alembic commands ###
